### ISSUE TITLE
Convert single .obj to .fbx

### ISSUE THREAD

**Issue by rlleshi** [yfeng95/PIXIE#9]
Any tips on how to convert the single `.obj` files to an animated sequence?

**Comment by Travvy88** [comment]
@rlleshi hey, did you find a method?

**Comment by rlleshi** [comment]
Hi @Travvy88 , I used [PARE](https://github.com/mkocabas/PARE). 

However, models like PIXIE/VIBE/PARE/SPIN/HMR/frakmocap use the so-called weak-perspective camera, which assumes that the movement in the depth dimension is small compared to the focal length. Therefore the depth of the person is not accurately estimated in these algorithms. This results in the so-called hip-lock problem where the human is just moving in place (and not around the space). 

Hence, if that is a problem for you, I would recommend using a model like [ROMP](https://github.com/Arthur151/ROMP).
